[project]
name = "atcoder-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aclogin>=0.2.1",
    "online-judge-template-generator>=4.8.1",
    "online-judge-tools>=11.5.1",
    "setuptools>=80.9.0",
]
